selenium/automate_chrome.sh, selenium/automate_firefox.sh, selenium/automate_opera.sh
=> Added selenoid/browser_name:latest tag

selenium/video/APKBUILD, selenium/video/Dockerfile, selenium/video/entrypoint.sh
=> new video image

selenium/video/entrypoint.sh
FIX: wait tcp listen xvfb
FEATURE: add option FRAME_RATE
=> FIX: wait tcp listen xvfb, add option FRAME_RATE

selenium/video/entrypoint.sh
This flag makes videos quickviewable on mac and viewable on ios devices
=> Quicktime compatible pixelformat on videos

selenium/base/base_4/fileserver/main.go, selenium/base/base_4/fileserver/main_test.go
=> Added file removal feature to fileserver

selenium/automate_android.sh
Use lastest version of build tools as recomended at https://developer.android.com/studio/releases/build-tools
=> Use 28.0.3 version of build-tools

README.md
=> Added example command for building images from Debian packages locally

selenium/chrome/local/Dockerfile
Fixes issue when building Chrome images from Debian packages #109
=> Update chrome local libraries

selenium/automate_yandex.sh, selenium/firefox/local/Dockerfile.tmpl, selenium/opera/blink/local/Dockerfile, selenium/yandex/local/Dockerfile
selenoid-container-tests passed for latest versions:
./automate_chrome.sh google-chrome-stable_78.0.3904.97-1_amd64.deb 78.0.3904.70 78.0
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_amd64.deb 1.9.3 70.0 0.26.0
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_i386.deb 1.9.3 70.0 0.26.0
./automate_opera.sh opera-stable_64.0.3417.92_amd64.deb 77.0.3865.120 64.0
./automate_yandex.sh yandex-browser-beta_19.9.3.358-1_amd64.deb 19.9.3 19.9
=> Update local dockerfiles

selenium/android/Dockerfile
New dependencies added to resolve libX* failures
=> Add new dependencies to Android docker file

README.md, selenium/automate_chrome.sh, selenium/automate_firefox.sh, selenium/automate_opera.sh, selenium/automate_yandex.sh, selenium/build-dev.sh, selenium/build.sh, selenium/chrome/apt/Dockerfile, selenium/chrome/local/Dockerfile, selenium/firefox/apt/Dockerfile.tmpl, selenium/firefox/local/Dockerfile.tmpl, selenium/opera/blink/apt/Dockerfile, selenium/opera/blink/local/Dockerfile, selenium/yandex/apt/Dockerfile, selenium/yandex/local/Dockerfile
selenoid-container-tests passed for latest versions of all combinations of browsers (Firefox, Chrome, Opera, Yandex), channels (Stable, Beta, Dev), methods (apt, local), and OS (Ubuntu, Mac):
./automate_firefox.sh 70.0.1+build1-0ubuntu0.18.04.1 1.9.3 70.0 0.26.0
./automate_chrome.sh 78.0.3904.108-1 78.0.3904.70 78.0
./automate_opera.sh 65.0.3467.42 78.0.3904.87 65.0
./automate_yandex.sh 19.9.3.358-1 19.9.3 19.9
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_amd64.deb 1.9.3 70.0 0.26.0
./automate_firefox.sh firefox_70.0.1+build1-0ubuntu0.18.04.1_i386.deb 1.9.3 70.0 0.26.0
./automate_chrome.sh google-chrome-stable_78.0.3904.108-1_amd64.deb 78.0.3904.70 78.0
./automate_opera.sh opera-stable_65.0.3467.42_amd64.deb 78.0.3904.87 65.0
./automate_yandex.sh …
=> Added support for browsers Beta and Dev channels

selenium/firefox/apt/Dockerfile.tmpl, selenium/firefox/local/Dockerfile.tmpl
Chrome and Firefox images were successfully tested with selenoid-container-tests passing.
=> Added iproute2 Linux utils to Firefox.

README.md, selenium/automate_chrome.sh, selenium/automate_firefox.sh, selenium/automate_opera.sh, selenium/automate_yandex.sh, selenium/build.sh, selenium/firefox/local/Dockerfile.tmpl
=> Add support to automatically use latest Drivers and Selenoid versions

selenium/android/Dockerfile, selenium/automate_android.sh
Add interactive parameter for Application Binary Interface. Default value to current one (x86).
=> Add parameter for Android ABI

selenium/android/entrypoint.sh, selenium/base/Dockerfile, selenium/base/fileserver/main.go, selenium/base/permissions.sh, selenium/opera_presto/Dockerfile, static/chrome/apt/Dockerfile, static/chrome/entrypoint.sh, static/chrome/local/Dockerfile, static/firefox/apt/Dockerfile, static/firefox/local/Dockerfile, static/firefox/selenium/entrypoint.sh, static/firefox/selenoid/Dockerfile, static/firefox/selenoid/entrypoint.sh, static/opera/apt/Dockerfile, static/opera/entrypoint.sh, static/opera/local/Dockerfile, static/yandex/apt/Dockerfile, static/yandex/entrypoint.sh, static/yandex/local/Dockerfile
=> Openshift permissions fix

build/chrome.go
- Handled situation where there is no compatible ChromeDriver available for Chrome Dev channel.
- Modified code to fail fast when the above happens.
- Removed unnecessary loop which was not using loop variable anyway.
=> Fixed ChromeDriver version selection

build/chrome.go, build/file.go, build/yandex.go
- This implementation is still the only valid one, since https://github.com/yandex/YandexDriver/issues/3 is still open
- Regression tested all browsers for all channels with apt method
=> Fixed YandexDriver version selection + refactoring

build/chrome.go, build/edge.go, cmd/edge.go, cmd/root.go, docs/building-images.adoc, selenium/android/Dockerfile, selenium/base/Dockerfile, selenium/base/fileserver/go.mod, selenium/external-host/Dockerfile, static/chrome/Dockerfile, static/edge/Dockerfile, static/edge/apt/Dockerfile, static/edge/entrypoint.sh, static/edge/local/Dockerfile
=> Support for building MicrosoftEdge Linux images (related to #302)

static/edge/entrypoint.sh
=> Removed devtools startup from edge image entrypoint (related to #302)

selenium/base/xseld/main.go
Fixes https://github.com/aerokube/selenoid/issues/1092
=> Fix xseld on ubuntu 20

selenium/android/Dockerfile
updated node version from 10 to 12
=> updated node version

build/chrome.go
If no matching ChromeDriver major version is available for Stable or Beta channel, then use the previous ChromeDriver version as we currently do for Dev channel.
Motivations for this change:
- For most of Chrome 92 Beta development life cycle, there was no matching ChromeDriver 92 available.
- Since ChromeDriver 91 release, it's possible to interact with a higher major version of Chrome on the Stable and Beta channels (i.e. chromedriver:91.0.4472.101 with google-chrome-stable:92.0.4515.107-1).
=> Improved ChromeDriver version selection

selenium/automate_android.sh
added support for building android 12.0 images using automate_android.sh
=> added support for building android 12.0 images

static/edge/entrypoint.sh
=> Allowing any origin for edgedriver too (related to #1229)
